- hosts: all
  become: true

  tasks:
  - name: Change the hostname
    hostname:
      name: "{{ inventory_hostname }}"
    when:
      ansible_fqdn != ansible_ssh_host  

- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true

  roles:
  - role: ipaserver
    state: present
