- hosts: all
  become: true

  tasks:
  - name: Change the hostname
    hostname:
      name: "{{ inventory_hostname }}"
    when:
      ansible_fqdn != ansible_ssh_host  

- name: Playbook to configure IPA replicas
  hosts: ipareplicas
  become: true

  roles:
  - role: ipareplica
    state: present
